name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: Linux setup
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install \
          g++-11 \
          mingw-w64 \
          clang-12 \
          autoconf \
          automake \
          autotools-dev \
          autopoint \
          libtool \
          pkg-config \
          libssl-dev \
          libc-ares-dev \
          zlib1g-dev \
          libsqlite3-dev \
          libssh2-1-dev \
          libcppunit-dev \
          libgmp-dev
    - name: Libtool
      run: |
        autoreconf -i
    - name: Configure autotools (Linux)
      if: runner.os == 'Linux'
      run: |
        HOST=x86_64-w64-mingw32 ./mingw-config
    - name: Build aria2
      run: |
        make -j"$(nproc 2> /dev/null || sysctl -n hw.ncpu)" check
    - name: Ls
      run: ls -lsall src

  build-docker:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3
    - name: Linux setup
      run: |
        docker build -t aria2-mingw - < Dockerfile.mingw
        id=$(docker create aria2-mingw)
        docker cp $id:/aria2/src/aria2c.exe .
        docker rm -v $id
        ls -lsall
